Домашнее задание React + Redux
TinaevNK/react-redux-hh pull request #1
Opened 2023-02-13 07:53 UTC by TinaevNK

# ***Проект GitHub Reviewers***
Проект является домашней работой в школе программистов ***HeadHunter*** по теме React и Redux.
## *Описание*
----
### ***О чём проект?***

Данное веб-приложение призвано помочь найти ревьюера в конкретном репозитории, исходя из списка контрибьютеров

Деплой проекта располагается [тут](https://tinaevnk.github.io/react-redux-hh/).

<p align="center"><a href="https://tinaevnk.github.io/react-redux-hh/" target="_blank"><img src="https://sun9-46.userapi.com/impg/6cLy8vBsvkkWKnHcb5bausu-wDQB99w9FPQTIA/oWM9xMCNMO8.jpg?size=1392x685&quality=96&sign=f5f5596cea85a09433972220f8d0393f&type=album" width="700px"></a></p>

***В нём представлены:***

Лендинг c кратким описанием:
  + Бургерное меню настроек для поиска ревьюера (поля ввода, кнопка валидации и сохранения, чёрный список ревьюеров)
  + Кнопка поиcка
  + Информация о владельце репозитория и проверяющего

---
## *Функциональность:*
* Реализована "живая" **валидация** полей ввода, не позволяющая начать поиск, если хотя бы одно поле не заполнено
* Использование собственных **хуков** (типизированные useSelector и useDispatch)
* Приложение использует API [GitHub](https://docs.github.com/en/rest)
* **Запоминание** состояния полей ввода (в форме настроек), (при обновлении страницы сохранённые данные не будут утеряны)
* Поиск регистронезависмый
* Выбор нежелательных ревьюеров в **чёрный список** (мультиселект по доступным контрибьюторам репозитория)
* При загрузке данных показывается **прелоадер** на кнопке валидации. По окончанию загрузки он скрывается. В случае ошибки - видим красную подсветку кнопки
* Полноценый **респонсив** для всех популярных разрешений экрана
* Утилитарные функции, константы, функции обращения к серверу вынесены в отдельный файлы
* Реализована **микроанимация** всех ссылок и кнопок
* Для создания сеток используется **flex** и **grid**

---
## *Используемые технологии:*

* React 18
* CSS Modules
* Redux 4
* Redux-thunk
* TypeScript 4
* Ant Design
---
## *Планы по доработке:*
* Доработать адаптивность
* Добавить тултипы о возникающих ошибках
* Перевести проект на Redux Toolkit
---
## *Директории:*

`/api` — папка с файлами для обращения к серверу

`/components` — папка с фунциональными компонентами

`/store` — папка c файлами, необходимыми для работы с Redux

`/vendor` — папка с кодом сторонних разработчиков

`/utils` — папка с файлами, требуемых для работы сервиса (кастомные хуки,константы)

---
## *Запуск проекта:*
`yarn` — установка зависимостей

`yarn start` — запускает приложение

---
## *Ссылки:*

* Домен по которому доступно приложение [https://tinaevnk.github.io/react-redux-hh/](https://tinaevnk.github.io/react-redux-hh/)
* Дока по API GitHub [https://docs.github.com/en/rest](https://docs.github.com/en/rest)

2023-02-13 15:37 UTC, AndreyGladkov requested changes
Спасибо за решение, по реакту там один комментарий, по поводу мемоизации. Остальные комментарии больше для информации.

2023-02-13 15:37 UTC, AndreyGladkov commented on src/components/BlackList/BlackList.tsx
> +  const contributorsOptions = useMemo(
проблема описана тут:
https://github.com/novvember/hh-reviewer-finder/pull/1/files#r1090295214

2023-02-13 15:37 UTC, AndreyGladkov commented on src/components/Header/Header.tsx
> +import s from "./header.module.css";
jfyi мы сокращения не используем, если это не аббревиатура)

2023-02-13 15:37 UTC, AndreyGladkov commented on src/components/Main/Main.tsx
> +    const set = new Set(blacklist);
jfyi set в данном случае лишний можно просто blacklist.includes

2023-02-14 07:01 UTC, TinaevNK commented on src/components/BlackList/BlackList.tsx
> +  const contributorsOptions = useMemo(
спасибо, поправил!
Не учёл данный момент

Я правильно понимаю, что если я добавлю в useCallback функцию клика по селекту, то у меня будет происходить только перерендер селекта, но не всего компонента настроек, так ведь?

Изначально с такой идеей писал

2023-02-14 07:11 UTC, TinaevNK commented on src/components/Header/Header.tsx
> +import s from "./header.module.css";
буду уметь ввиду, хорошо)
не хотел раздувать код

обычно использую [React CSS Modules](https://www.npmjs.com/package/react-css-modules). Такое решение в ХХ используют? кажется довольно удобным, но в этой работе не стал применять

Ещё использую [classnames](https://www.npmjs.com/package/classnames)

2023-02-14 07:17 UTC, TinaevNK commented on src/components/Main/Main.tsx
> +    const set = new Set(blacklist);
Да, можно includes, заменил)

Я пожертвовал памятью, но зато поиск по Set происходит за O(1) - поэтому и решил так сделать, чтобы много раз линейно не проходиться))

2023-02-14 07:22 UTC, AndreyGladkov commented on src/components/BlackList/BlackList.tsx
> +  const contributorsOptions = useMemo(
пока не поправил), ну изменения не запушены.

>Я правильно понимаю, что если я добавлю в useCallback функцию клика по селекту, то у меня будет происходить только перерендер селекта, но не всего компонента настроек, так ведь?

Нет ты неправильно понял.  useCallback мемоизирует функцию, в случае если свойства от которых он зависит не изменились, useCallback вернет старую ссылку на функцию. С useMemo история такая же, только он возвращает мемоизированное значение, которое может и по ссылке и по значению передаваться. Так вот, когда ты передаешь эти данные в компонент, то ты добавляешь оптимизации в плане 
рендера тому компоненту для которого ты передал эти свойства, в данном случае это select.
Но опять же у тебя в select передаются и другие значения типо:
```
style={{ width: "100%" }}
```
этот проп сводит на нет все попытки добавить мемоизации, потому как он будет также формировать новую ссылку на объект при любом ререндере компонента BlackList.

Ну и для того, чтобы работало:
1) надо обернуть в memo ребенка
2) передавать одинаковые ссылки | значения при ререндере

Есть еще кейс когда мемоизируются какие-то сложные вычисления, тогда тоже используется useMemo, чтобы не делать их на каждый ререндер. Но это как правило cpu bound операции.

2023-02-14 07:37 UTC, AndreyGladkov commented on src/components/Header/Header.tsx
> +import s from "./header.module.css";
так это оно же и есть =) да мы используем css modules, и classnames тоже

2023-02-14 08:31 UTC, merged